# diffheat/__init__.py
"""diffheat — Differentiable heat equation simulations with JAX."""
import logging

from .mesh import (
    BoundaryCondition,
    BoundaryCondition2D,
    BoundaryCondition3D,
    Grid1D,
    Grid2D,
    Grid3D,
    PolarGrid,
    apply_boundary_conditions_1d,
    apply_boundary_conditions_3d,
)
from .operators import (
    divergence_2d,
    divergence_3d,
    gradient_1d,
    gradient_2d,
    gradient_3d,
    gradient_x3d,
    gradient_y3d,
    gradient_z3d,
    laplacian_1d,
    laplacian_2d,
    laplacian_3d,
    make_laplacian,
)
from .analysis import (
    check_maximum_principle_2d,
    check_mean_value_2d,
    compute_nodal_lines_2d,
    compute_nodal_lines_disc,
)
from .physics import (
    HeatEquation1D,
    HeatEquation2D,
    HeatEquation3D,
    WaveEquation1D,
    WaveEquation2D,
    WaveEquation3D,
    TelegrapherEquation1D,
    TelegrapherEquation2D,
    TelegrapherEquation3D,
    apply_boundary_conditions,
    bessel_j_zero,
    eigenfunction_disc,
    eigenfunction_norm,
    eigenvalue_disc,
)
from .solvers import (
    check_cfl,
    check_cfl_2d,
    check_cfl_3d,
    check_cfl_wave_1d,
    check_cfl_wave_2d,
    check_cfl_wave_3d,
    check_cfl_telegrapher_1d,
    check_cfl_telegrapher_2d,
    check_cfl_telegrapher_3d,
    explicit_euler_step,
    explicit_euler_step_1d,
    explicit_euler_step_2d,
    explicit_euler_step_3d,
    find_first_eigenvalue_1d,
    find_first_eigenvalue_2d,
    find_first_eigenvalue_3d,
    rayleigh_quotient_1d,
    rayleigh_quotient_2d,
    rayleigh_quotient_3d,
    rayleigh_upper_bounds_1d,
    rayleigh_upper_bounds_2d,
    rayleigh_upper_bounds_3d,
    solve_1d,
    solve_2d,
    solve_3d,
    solve_heat_1d,
    solve_heat_2d,
    solve_heat_3d,
    solve_heat_inhomogeneous_2d,
    solve_heat_inhomogeneous_3d,
    solve_steady_state_1d,
    solve_steady_state_2d,
    solve_steady_state_3d,
    solve_wave_1d,
    solve_wave_2d,
    solve_wave_3d,
    solve_telegrapher_1d,
    solve_telegrapher_2d,
    solve_telegrapher_3d,
    solve_heat_disc_analytical,
    solve_steady_state_disc,
    solve_steady_state_cylinder_3d,
)
from .utils import array, get_default_dtype, get_device

_logger = logging.getLogger(__name__)
_logger.info(f"diffheat running on: {get_device()}")

__all__ = [
    # Mesh — 1D
    "Grid1D",
    "BoundaryCondition",
    "apply_boundary_conditions_1d",
    # Mesh — 2D
    "Grid2D",
    "BoundaryCondition2D",
    "apply_boundary_conditions_2d",
    # Mesh — 3D
    "Grid3D",
    "BoundaryCondition3D",
    "apply_boundary_conditions_3d",
    # Mesh — Polar
    "PolarGrid",
    # Operators — 1D
    "make_laplacian",
    "laplacian_1d",
    "gradient_1d",
    # Operators — 2D
    "laplacian_2d",
    "gradient_2d",
    "divergence_2d",
    # Operators — 3D
    "laplacian_3d",
    "gradient_3d",
    "gradient_x3d",
    "gradient_y3d",
    "gradient_z3d",
    "divergence_3d",
    # Physics — Heat
    "HeatEquation1D",
    "HeatEquation2D",
    "HeatEquation3D",
    "apply_boundary_conditions",
    # Physics — Wave
    "WaveEquation1D",
    "WaveEquation2D",
    "WaveEquation3D",
    # Physics — Telegrapher
    "TelegrapherEquation1D",
    "TelegrapherEquation2D",
    "TelegrapherEquation3D",
    # Physics — Bessel
    "bessel_j_zero",
    "eigenvalue_disc",
    "eigenfunction_disc",
    "eigenfunction_norm",
    # Solvers — 1D
    "explicit_euler_step",
    "explicit_euler_step_1d",
    "solve_heat_1d",
    "solve_1d",
    "solve_wave_1d",
    "solve_telegrapher_1d",
    "solve_heat_disc_analytical",
    "check_cfl",
    "check_cfl_wave_1d",
    "check_cfl_telegrapher_1d",
    "solve_steady_state_1d",
    "rayleigh_quotient_1d",
    "rayleigh_upper_bounds_1d",
    "find_first_eigenvalue_1d",
    # Solvers — 2D
    "explicit_euler_step_2d",
    "solve_heat_2d",
    "solve_2d",
    "solve_wave_2d",
    "solve_telegrapher_2d",
    "check_cfl_2d",
    "check_cfl_wave_2d",
    "check_cfl_telegrapher_2d",
    "solve_steady_state_2d",
    "solve_steady_state_disc",
    "solve_steady_state_cylinder_3d",
    "solve_heat_inhomogeneous_2d",
    "rayleigh_quotient_2d",
    "rayleigh_upper_bounds_2d",
    "find_first_eigenvalue_2d",
    # Solvers — 3D
    "explicit_euler_step_3d",
    "solve_heat_3d",
    "solve_3d",
    "solve_wave_3d",
    "solve_telegrapher_3d",
    "check_cfl_3d",
    "check_cfl_wave_3d",
    "check_cfl_telegrapher_3d",
    "solve_steady_state_3d",
    "solve_heat_inhomogeneous_3d",
    "rayleigh_quotient_3d",
    "rayleigh_upper_bounds_3d",
    "find_first_eigenvalue_3d",
    # Analysis
    "compute_nodal_lines_2d",
    "compute_nodal_lines_disc",
    "check_mean_value_2d",
    "check_maximum_principle_2d",
    # Utils
    "get_device",
    "get_default_dtype",
    "array",
]

