"""Pure-JAX physics of heat-driven cooling (``../DESIGN.md`` §4).

This subpackage imports only ``jax``/``numpy`` and itself — no env, backend,
data, or optimizer imports (enforced by import-linter, root pyproject).
"""

from . import absorption, bed1d, boussinesq, cloak2d, cycle0d, forced_conv, heat1d, heat2d, heat3d, natural_conv, system, te_1d, telegrapher, thermo, thermoelectric
from .bed1d import (
    SERIES_CHANNELS,
    advance_carry,
    bed_rhs,
    check_timestep,
    cycle_totals_from_carry,
    initial_carry,
    ldf_rate,
    max_timestep,
    simulate_bed,
    step_bed,
    step_episode,
    summary_from_carry,
    vapor_step,
    volumetric_capacity,
)
from .cycle0d import METRIC_KEYS, simulate_cycle
from .heat1d import HeatEquation1D, heat_rhs_1d, simulate_heat_1d, solve_heat_1d
from .heat2d import HeatEquation2D, heat_rhs_2d, simulate_heat_2d, solve_heat_2d
from .heat3d import HeatEquation3D, heat_rhs_3d, simulate_heat_3d, solve_heat_3d
from .system import (
    SYSTEM_SERIES_CHANNELS,
    advance_two_carry,
    bed_phys,
    initial_two_carry,
    simulate_two_bed,
    summary_from_two_carry,
)
from .thermo import (
    CP_ADSORBENT,
    CP_LIQUID,
    GAS_CONSTANT,
    da_uptake,
    water_h_fg_j_kg,
    water_sat_pressure_pa,
)

__all__ = [
    "CP_ADSORBENT",
    "CP_LIQUID",
    "GAS_CONSTANT",
    "METRIC_KEYS",
    "SERIES_CHANNELS",
    "SYSTEM_SERIES_CHANNELS",
    "advance_carry",
    "advance_two_carry",
    "absorption",
    "bed1d",
    "bed_phys",
    "bed_rhs",
    "boussinesq",
    "check_timestep",
    "cloak2d",
    "cycle0d",
    "cycle_totals_from_carry",
    "da_uptake",
    "HeatEquation1D",
    "HeatEquation2D",
    "HeatEquation3D",
    "heat1d",
    "heat2d",
    "heat3d",
    "heat_rhs_1d",
    "heat_rhs_2d",
    "heat_rhs_3d",
    "initial_carry",
    "initial_two_carry",
    "ldf_rate",
    "max_timestep",
    "simulate_bed",
    "simulate_cycle",
    "simulate_heat_1d",
    "simulate_heat_2d",
    "simulate_heat_3d",
    "solve_heat_1d",
    "solve_heat_2d",
    "solve_heat_3d",
    "simulate_two_bed",
    "forced_conv",
    "natural_conv",
    "step_bed",
    "step_episode",
    "summary_from_carry",
    "summary_from_two_carry",
    "system",
    "te_1d",
    "telegrapher",
    "thermo",
    "thermoelectric",
    "vapor_step",
    "volumetric_capacity",
    "water_h_fg_j_kg",
    "water_sat_pressure_pa",
]
